export const SET_MICROMESSENGER = 'SET_MICROMESSENGER';
export const SETIPHONEX = 'SETIPHONEX';
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const SET_TOKEN = 'SET_TOKEN';
export const CHANGE_NICKNAME = 'CHANGE_NICKNAME';
